packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ~5.6.2
  superjson: ^2.2.1
  zod: ^3.23.8
  "@trpc/server": 11.0.0-rc.638
  "@trpc/client": 11.0.0-rc.638
  drizzle-kit: ^0.28.1
  fp-ts: ^2.16.9
  io-ts: ^2.2.21
  io-ts-reporters: ^2.0.1
  io-ts-types: ^0.5.19
