export const CategoriesBatch = {
  'Fresh food and bakery': [
    'category1NI:Fruit & Vegetables',
    'category1NI:Butchery',
    'category1NI:Seafood',
    'category1NI:Deli, Salads & Cooked Meats',
    'category1NI:Bakery',
    'category1NI:Dairy & Eggs',
    'category1NI:Bulk & Loose Foods',
  ],
  'Chilled Frozen and Desserts': [
    'category1NI:Dairy & Eggs',
    'category1NI:Cheese',
    'category1NI:Desserts',
    'category1NI:Frozen Foods',
  ],
  'Beer and Wine': ['category1NI:Beer & Cider', 'category1NI:Wine'],
  'Personal Care': [
    'category1NI:Beauty & Grooming',
    'category1NI:Health & Wellness',
  ],
  'Baby care': ['category1NI:Baby Care'],
  Pantry: [
    'category1NI:Baking Supplies & Sugar',
    'category1NI:Biscuits & Crackers',
    'category1NI:Breakfast Cereals',
    'category1NI:Canned & Prepared Foods',
    'category1NI:Condiments & Dressings',
    'category1NI:Confectionery',
    'category1NI:Hot Drinks',
    'category1NI:Jams, Honey & Spreads',
    'category1NI:Pasta, Rice & Noodles',
    'category1NI:Salad & Cooking Oils',
    'category1NI:Sauces, Stock & Marinades',
    'category1NI:Snack Foods',
    'category1NI:Spices & Seasonings',
    'category1NI:World Foods',
  ],
  Drinks: ['category1NI:Cold Drinks', 'category1NI:Hot Drinks'],
  Pets: ['category1NI:Pet Supplies'],
  'Kitchen dining and cleaning': [
    'category1NI:Cleaning Products',
    'category1NI:Garage & Outdoor',
    'category1NI:Household',
    'category1NI:Laundry',
    'category1NI:Stationery & Entertainment',
  ],
} as const;
