import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faDiscord,
  faPushed,
  faReddit,
} from "@fortawesome/free-brands-svg-icons";
import {
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBarcode,
  faBars,
  faBox,
  faBoxesStacked,
  faCartPlus,
  faCartShopping,
  faChevronDown,
  faChevronRight,
  faClock,
  faClose,
  faCloudDownload,
  faCopy,
  faDatabase,
  faDollarSign,
  faDownload,
  faEdit,
  faExclamationCircle,
  faExclamationTriangle,
  faExpand,
  faExternalLink,
  faExternalLinkAlt,
  faFileExport,
  faFileImport,
  faFloppyDisk,
  faFolderTree,
  faGauge,
  faIdCard,
  faLink,
  faLocation,
  faMagic,
  faMinus,
  faMoon,
  faPen,
  faPlay,
  faPlus,
  faQrcode,
  faRandom,
  faRotateRight,
  faSearch,
  faShare,
  faSpinner,
  faStop,
  faStore,
  faSun,
  faSync,
  faTachometerAlt,
  faTag,
  faThumbTack,
  faTrash,
  faUnlink,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

config.autoAddCss = false;

library.add(
  faReddit,
  faExternalLinkAlt,
  faSearch,
  faCartPlus,
  faSpinner,
  faStop,
  faCartShopping,
  faArrowRight,
  faExclamationTriangle,
  faDollarSign,
  faPlay,
  faClock,
  faExclamationCircle,
  faClose,
  faPlus,
  faMinus,
  faChevronRight,
  faChevronDown,
  faExternalLink,
  faSpinner,
  faSync,
  faClock,
  faDownload,
  faCloudDownload,
  faLocation,
  faStore,
  faTachometerAlt,
  faBars,
  faRotateRight,
  faPen,
  faFileExport,
  faFileImport,
  faRandom,
  faMagic,
  faArrowLeft,
  faUnlink,
  faBox,
  faBoxesStacked,
  faGauge,
  faFloppyDisk,
  faDatabase,
  faAsterisk,
  faIdCard,
  faTag,
  faTrash,
  faEdit,
  faDiscord as any,
  faLink,
  faBarcode,
  faQrcode,
  faCopy,
  faShare,
  faThumbTack,
  faPushed,
  faFolderTree,
  faExpand,
  faMoon,
  faSun,
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("fa", FontAwesomeIcon);
});
